name: qldt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  intl:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  google_sign_in: ^5.2.4

  get: ^4.6.1

  flutter_easyloading: ^3.0.3
  #Firestore.instance.collection(city).document('Attractions').updateData({"data": FieldValue.arrayUnion(obj)});
  cloud_firestore: ^3.1.15
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  progressive_image: ^2.0.0

  # flutter pub run build_runner build --delete-conflicting-outputs
  # muốn chạy lệnh flutter pub run build_runner build thì import build_runner
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  dropdown_button2: ^1.5.1
  table_calendar: ^3.0.5
  timelines: ^0.1.0
  syncfusion_flutter_calendar: ^20.1.58
  shared_preferences: ^2.0.15
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/hide_password.png
    - assets/icons/show_password.png
    - assets/icons/icon_google.png
    - assets/icons/logo_login.png
    - assets/icons/google_logo.png
    - assets/icons/logo_sign_up.png
    - assets/icons/ic_back.png
    - assets/icons/ic_classroom.png
    - assets/images/img_department_manager.png
    - assets/images/img_loading.gif
    - assets/images/img_loading_1.gif
    - assets/images/img_user_manager_item.png
    - assets/images/img_classroom.jpeg
    - assets/images/img_specialized.png
    - assets/images/img_subject_manage.png
    - assets/images/img_specialized_1.png
    - assets/images/img_course.png
    - assets/images/img_user.png
    - assets/icons/ic_specialized.png
    - assets/icons/ic_specialized_1.png
    - assets/icons/ic_specialized_2.png
    - assets/icons/ic_specialized_3.png
    - assets/icons/ic_specialized_4.png
    - assets/icons/ic_specialized_5.png
    - assets/icons/ic_specialized_6.png
    - assets/icons/ic_subject_selected.png
    - assets/icons/ic_book.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 100
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 200
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
